### ISSUE TITLE
Use CLJSJS for Google-Maps example

### ISSUE THREAD

**Issue by TerjeNorderhaug** [reagent-project/reagent-cookbook#37]
The [google-maps cljsjs package](https://github.com/cljsjs/packages/tree/master/google-maps) can be required instead of declaring custom externs in the Google Maps example. Same for [highcharts externs](https://github.com/cljsjs/packages/tree/master/highcharts).

**Comment by gadfly361** [comment]
@TerjeNorderhaug Thanks for the issue, always appreciate feedback!

While I personally use CLJSJS in production, there have been instances where I need to augment it with custom externs because CLJSJS doesn't always have complete/accurate coverage.  With this in mind, the recipes intentionally use custom externs instead of CLJSJS.

I am open to PRs that add links to CLJSJS in the recipes though :)
