### ISSUE TITLE
Recipe correction for google-maps recipe

### ISSUE THREAD

**Issue by EvanMisshula** [reagent-project/reagent-cookbook#47]
I was unable to get the google map to render until I corrected the home function:

[:div [(r/create-class ...)]] 

as shown in the third comment of this  Stack Overflow answer:

https://stackoverflow.com/questions/38632718/adding-google-maps-to-luminus-reagent-page  by Walton Hoops.

Let me know if you would consider a pull request.  Thank you for all your great work on this project. 

Best,
Evan

**Comment by gadfly361** [comment]
@EvanMisshula Thanks for opening this issue! Always happy for feedback and support :) 

I am content with the current recipe's recommendation to add the google maps script to the index.html, so no PR is necessary.

Regarding the question in stack overflow, I think another problem was that `map-page` was not returning a single element ... instead it was trying to return two (the script and the div). The script was being dropped on the floor, because react renders one element, in this case it would be the div.container.

(defn map-page []
  [:script {:type "text/javascript" :src "https://maps.googleapis.com/maps/api/js?key=<mykey>"}]
  [:div.container
   [:div.row
    [:div.col-md-12
     (r/create-class {:reagent-render      home-render
                      :component-did-mount home-did-mount})]]])

Best,
Matt
